apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc002
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc003
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi