apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-wp-config
data:
  site.conf: |-
    server {
        listen          80;
        server_name     localhost;
        root            html;
        index           index.php index.html;

        try_files $uri $uri/ @rewrite; #检测uir是否存在，不存在就去查找@rewrite的值

        location @rewrite {
            rewrite ^/(.*)$ /index.php?_url=/$1;
        }
        error_page  500 502 503 504 /50x.html;

        location = /50x.html {
                root html;
        }

        location ~ [^/]\.php(/|$) {
                fastcgi_pass 10.254.27.220:9000;
                fastcgi_index index.php;
                include fastcgi.conf;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-nginx
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
  sessionAffinity: clientIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc02
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-nginx
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: 192.168.100.200:80/library/nginx:v1
        ports:
        - containerPort: 80
          name: wordpress
        VolumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /usr/local/nginx/html
        - name: config
          mountPath: /usr/local/nginx/conf/vhost/site.conf
          subPath: site.conf
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc02
      - name: config
        configMap:
          name: nginx-wp-config




